<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Crch.ItBudget.Application/Crch.ItBudget.Application.csproj" />
    <ProjectReference Include="../Crch.ItBudget.Domain/Crch.ItBudget.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>
</Project>
