<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../LedgerForge.Application/LedgerForge.Application.csproj" />
    <ProjectReference Include="../LedgerForge.Domain/LedgerForge.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>
</Project>
