<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Crch.ItBudget.Application/Crch.ItBudget.Application.csproj" />
    <ProjectReference Include="../Crch.ItBudget.Domain/Crch.ItBudget.Domain.csproj" />
    <ProjectReference Include="../Crch.ItBudget.ImportExport/Crch.ItBudget.ImportExport.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
