<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Crch.ItBudget.Application/Crch.ItBudget.Application.csproj" />
    <ProjectReference Include="../Crch.ItBudget.Infrastructure/Crch.ItBudget.Infrastructure.csproj" />
    <ProjectReference Include="../Crch.ItBudget.Reporting/Crch.ItBudget.Reporting.csproj" />
    <ProjectReference Include="../Crch.ItBudget.ImportExport/Crch.ItBudget.ImportExport.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.0" />
  </ItemGroup>
</Project>
